package org.test.kotlinsdk


fun AssumedRoleUserMin.Companion.javaBuilder(): AssumedRoleUserMinBuilder = AssumedRoleUserMinBuilder()

class AssumedRoleUserMinBuilder() {
    private val sourceType = AssumedRoleUserMin.Builder();

    fun build(): AssumedRoleUserMin {
        return sourceType.build();
    }
    /**
     * The ARN of the temporary security credentials that are returned from the AssumeRole action. For more information about ARNs and how to use them in
     * policies, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers in the
     * IAM User Guide.
     */
    fun arn(arn: String): AssumedRoleUserMinBuilder {
        this.sourceType.arn = arn
        return this
    }
    /**
     * A unique identifier that contains the role ID and the role session name of the role that
     * is being assumed. The role ID is generated by Amazon Web Services when the role is created.
     */
    fun assumedRoleId(assumedRoleId: String): AssumedRoleUserMinBuilder {
        this.sourceType.assumedRoleId = assumedRoleId
        return this
    }
}
